FROM maven:3.9.4-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar api-gateway.jar
EXPOSE 4000
ENTRYPOINT ["java", "-jar", "api-gateway.jar"]