spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://localhost:5432/deseases
spring.datasource.username=postgres
spring.datasource.password=bestuser
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true